# Packages for LinuxMint Wilma

"title" = "Complementary Packages for LinuxMint Wilma"

[general]
"arp-scan" = ""
"bluetooth" = ""
"build-essential" = ""
"default-jdk" = ""
"fd-find" = ""  # command: fdfind 
"ffmpeg" = ""
"fsarchiver" = ""
"geany" = ""
"gimp" = ""
"git" = ""
"git-extras" = ""
"gnome-system-tools" = ""
"gparted" = ""
# "guile-3.0" = ""  # install guile-3.0-dev 
"guile-3.0-dev" = "" # Gnu scheme
# "libssl-dev" = "" #[Python]
"libgtk2.0-dev" = ""
"librsvg2-bin" = ""
"libsqlite3-dev" = ""
"members" = ""
# "mit-scheme" = "" #[use Guile instead] 
"most" = ""
"nmap" = ""
"openssh-client" = ""
"openssh-server" = ""
"pandoc" = ""
"pkg-config " = ""
"podman" = ""
# "qtcreator" = "" # unused
"rdiff-backup" = ""
"restic" = ""
"skopeo" = ""
"software-properties-common" = "" # apt-add-repository
"sshfs" = ""
"stow" = ""
"terminator" = ""
"tree" = ""
"uidmap" = ""
"vlc" = ""
"wl-clipboard" = ""
"xclip" = ""
"xsel" = ""

[Python]
# "bzip2" = ""
# "gcc" = ""
# "gdb" = ""
# "lcov" = ""
"libbz2-dev" = ""
# "libdb5.3-dev" = ""
# "libexpat1-dev" = ""
# "libffi-dev" = ""
# "libgc-dev" = ""
# "libgdbm-compat-dev" = ""
# "libgdbm-dev" = ""
# "liblzma-dev" = ""
# "libmpd-dev" = ""
# "libncurses5-dev" = ""
# "libncursesw5-dev" = ""
# "libreadline-dev" = ""
# "libreadline6-dev " = ""
# "libsqlite3-dev" = "" # in [general]
"libssl-dev" = ""
# "libssl3" = ""
# "libxcb-cursor-dev" = ""
# "libxcb-cursor0" = ""
# "libxml2-dev" = ""
# "libxmlsec1-dev" = ""
# "lzma " = ""
# "lzma-dev" = ""
# "make" = "" # build-essential in [general]
# "openssl" = "" # [general]
# "patch" = ""
# "pkg-config " = ""
# "python3-cffi " = ""
# "python3-dev" = "" # not needed
# "python3-tk" = ""  # not needed
# "python3-venv" = "" # not needed
# "qt6-wayland" = ""  # not yet
# "qt6-wayland-dev" = "" #not yet
# "qt6-wayland-dev-tools" = "" #not yet
# "software-properties-common" = "" # install in [general]
# "sqlite3" = ""
"tk-dev" = ""
# "uuid-dev" = ""
# "xz-utils" = ""
# "zlib1g-dev" = ""

[Emacs] # ## https://gist.github.com/zoliky/0445b20676bfa85450d7df006066ceb7
"autoconf" = ""
"automake" = ""
"libgif-dev" = ""
"libjpeg-dev" = ""
"libmagickwand-dev" = ""
"libncurses-dev" = ""
"libpng-dev" = ""
"libtiff-dev" = ""
"libtree-sitter-dev" = ""
"libwebkit2gtk-4.0-dev" = "deb http://gb.archive.ubuntu.com/ubuntu jammy main"
"libx11-dev" = ""
"libxpm-dev" = ""
"texinfo" = ""